// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwiltdsextydytyihzoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3aWx0ZHNleHR5ZHl0eWloem9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTM4NDgsImV4cCI6MjA2MjUyOTg0OH0.0Z4esAbn8S0g1gDsRJ8JEOysdwOcKOKjwjKxSInrZlA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);